// =============================================================================
// audio.rs — Enhanced audio passthrough configuration for Pi 5 HDMI output
// =============================================================================
//
// INTEGRATION NOTES — changes needed in other files (DO NOT apply automatically):
//
// 1. device_profile.rs — update `pi5_vlc()`:
//    - Add a dedicated DirectPlayProfile for Audio (profile_type: "Audio") with
//      codecs from AudioPassthrough::direct_play_codecs():
//        container: "mp3,flac,ogg,oga,opus,webma,m4a,m4b,aac,wav,wma,aiff"
//        audio_codec: Some("ac3,eac3,dts,truehd,flac,aac,mp3,opus,vorbis")
//    - Add a TranscodingProfile for Audio with:
//        container: "ts", audioCodec: "aac" (fallback), maxAudioChannels: "2"
//    - Add CodecProfile conditions for audio channel limits:
//        * codec "ac3"    -> AudioChannels LessThanEqual "6"
//        * codec "eac3"   -> AudioChannels LessThanEqual "8" (Atmos-capable)
//        * codec "dts"    -> AudioChannels LessThanEqual "6"
//        * codec "truehd" -> AudioChannels LessThanEqual "8" (Atmos-capable)
//    - Update the existing video DirectPlayProfile's audio_codec list to match
//      AudioPassthrough::direct_play_codecs() output.
//
// 2. config.rs — expand PlaybackConfig:
//    - Replace `audio_passthrough: bool` with `audio_passthrough: AudioPassthrough`
//      (or keep the bool and add a separate `audio_codecs: AudioPassthrough` field).
//    - Derive Serialize + Deserialize on AudioPassthrough for TOML config support.
//    - Update Default impl to use AudioPassthrough::default_safe().
//
// 3. player/vlc.rs — use AudioPassthrough::vlc_args():
//    - In `play_url()`, replace the hardcoded `--spdif` arg block (lines ~222-225)
//      with args generated by AudioPassthrough::vlc_args().
//    - Example:
//        let audio_config = AudioPassthrough::default_safe(); // or from AppConfig
//        args.extend(audio_config.vlc_args());
//    - Remove the hardcoded `--alsa-audio-device default` if vlc_args() provides
//      an explicit ALSA device for HDMI passthrough.
//

use log::{debug, info, warn};

/// Audio codec passthrough capabilities for Pi 5 HDMI output.
///
/// Controls which audio codecs are passed through (bitstream) to an external
/// receiver/soundbar via HDMI, versus decoded to PCM by VLC on the Pi itself.
///
/// Passthrough means the compressed audio bitstream is sent unchanged over
/// HDMI/SPDIF — the AV receiver handles decoding. This preserves lossless
/// formats (TrueHD, DTS-HD MA) and object-based audio (Atmos, DTS:X).
#[derive(Debug, Clone)]
pub struct AudioPassthrough {
    /// Dolby Digital (AC-3) — up to 5.1ch, 640 kbps. Universally supported.
    pub ac3: bool,
    /// Dolby Digital Plus (E-AC-3) — up to 7.1ch (15.1 with Atmos).
    /// Requires HDMI 1.3+. Also the carrier for Dolby Atmos over streaming.
    pub eac3: bool,
    /// DTS (Digital Theater Systems) — up to 5.1ch, 1.5 Mbps.
    /// Widely supported on AV receivers manufactured after ~2000.
    pub dts: bool,
    /// DTS-HD Master Audio — lossless, up to 7.1ch, ~25 Mbps peak.
    /// Requires HDMI 1.3+ and a DTS-HD capable receiver.
    pub dts_hd: bool,
    /// Dolby TrueHD — lossless, up to 7.1ch (with Atmos metadata).
    /// Requires HDMI 1.3+ and a TrueHD-capable receiver. Common on Blu-ray.
    pub truehd: bool,
    /// AAC — always direct play (decoded by VLC, no passthrough needed).
    /// Included here for device profile codec list generation only.
    pub aac: bool,
    /// FLAC — lossless PCM. Decoded locally by VLC (no HDMI passthrough path).
    /// Included here for device profile codec list generation only.
    pub flac: bool,
}

impl AudioPassthrough {
    /// Safe defaults: AC3 + DTS enabled.
    ///
    /// These two codecs are supported by virtually every HDMI-connected AV
    /// receiver and soundbar manufactured in the last 20 years. EAC3, TrueHD,
    /// and DTS-HD require explicit opt-in because many budget soundbars and
    /// older receivers will produce silence or noise when receiving them.
    pub fn default_safe() -> Self {
        Self {
            ac3: true,
            eac3: false,
            dts: true,
            dts_hd: false,
            truehd: false,
            aac: true,  // always on — decoded locally
            flac: true,  // always on — decoded locally
        }
    }

    /// Full passthrough: every bitstream format enabled.
    ///
    /// Use this when the HDMI sink (AV receiver) supports all formats.
    /// If the receiver does not actually support a format, you will get
    /// silence or digital noise on those tracks.
    pub fn full() -> Self {
        Self {
            ac3: true,
            eac3: true,
            dts: true,
            dts_hd: true,
            truehd: true,
            aac: true,
            flac: true,
        }
    }

    /// Generate VLC command-line arguments for audio passthrough.
    ///
    /// Strategy:
    /// - If any passthrough codec is enabled, use `--spdif` to tell VLC to
    ///   attempt bitstream output for supported codecs.
    /// - For HDMI-only formats (TrueHD, DTS-HD, EAC3), force the ALSA output
    ///   to the HDMI device so the bitstream reaches the receiver unmodified.
    /// - The `--audio-filter=scaletempo` is always added for variable-speed
    ///   playback support (VLC disables it automatically during passthrough).
    pub fn vlc_args(&self) -> Vec<String> {
        let mut args = Vec::new();

        // scaletempo for variable-speed playback — VLC automatically bypasses
        // this filter when outputting a compressed bitstream
        args.push("--audio-filter".to_string());
        args.push("scaletempo".to_string());

        let any_passthrough = self.ac3 || self.eac3 || self.dts || self.dts_hd || self.truehd;
        if !any_passthrough {
            // No passthrough at all — just decode everything to PCM
            info!("Audio passthrough: disabled, all codecs will be decoded to PCM");
            return args;
        }

        // --spdif tells VLC to pass compressed audio bitstreams through
        // instead of decoding them to PCM. Works for AC3, DTS, and (with
        // the right ALSA device) also EAC3, TrueHD, DTS-HD.
        args.push("--spdif".to_string());

        let needs_hdmi = self.truehd || self.dts_hd || self.eac3;
        if needs_hdmi {
            // TrueHD / DTS-HD MA / EAC3 require the raw HDMI output path.
            // SPDIF (optical/coax) cannot carry these formats — they exceed
            // the 1.5 Mbps SPDIF bandwidth limit.
            //
            // On Raspberry Pi 5, the HDMI ALSA device is typically
            // "hdmi:CARD=vc4hdmi0" (first HDMI port) or "hdmi:CARD=vc4hdmi1"
            // (second HDMI port). We default to vc4hdmi0.
            args.push("--aout=alsa".to_string());
            args.push("--alsa-audio-device=hdmi:CARD=vc4hdmi0".to_string());
            info!(
                "Audio passthrough: HDMI mode (TrueHD={}, DTS-HD={}, EAC3={})",
                self.truehd, self.dts_hd, self.eac3
            );
        } else {
            // AC3/DTS only — works over SPDIF or HDMI. Use default ALSA
            // device (which is usually HDMI anyway on a headless Pi).
            info!(
                "Audio passthrough: SPDIF mode (AC3={}, DTS={})",
                self.ac3, self.dts
            );
        }

        // Build the passthrough codec list for --avcodec-codec.
        // This tells VLC which codecs to pass through rather than decode.
        let mut codecs = Vec::new();
        if self.ac3 { codecs.push("ac3"); }
        if self.eac3 { codecs.push("eac3"); }
        if self.dts { codecs.push("dts"); }
        if self.dts_hd { codecs.push("dts"); } // DTS-HD uses same decoder name
        if self.truehd { codecs.push("truehd"); }

        // Deduplicate (dts appears once even if both dts and dts_hd are on)
        codecs.sort();
        codecs.dedup();

        if !codecs.is_empty() {
            args.push("--codec=avcodec".to_string());
            args.push(format!("--avcodec-codec={}", codecs.join(",")));
            debug!("Audio passthrough codecs: {}", codecs.join(", "));
        }

        args
    }

    /// Generate the audio codec list for Jellyfin DirectPlayProfile.
    ///
    /// Returns all codecs that this configuration can handle — either via
    /// passthrough (bitstream) or local decode (PCM). Jellyfin uses this
    /// list to decide whether to direct-play or transcode each audio stream.
    ///
    /// Codecs that are always locally decoded (AAC, FLAC, MP3, ALAC, etc.)
    /// are included unconditionally because VLC can always handle them.
    pub fn direct_play_codecs(&self) -> Vec<String> {
        let mut codecs = Vec::new();

        // Passthrough codecs — only advertise if enabled
        if self.ac3 { codecs.push("ac3".to_string()); }
        if self.eac3 { codecs.push("eac3".to_string()); }
        if self.dts { codecs.push("dts".to_string()); }
        if self.dts_hd { codecs.push("dts".to_string()); } // Jellyfin uses "dts" for both
        if self.truehd { codecs.push("truehd".to_string()); }

        // Locally decoded codecs — always supported
        if self.aac { codecs.push("aac".to_string()); }
        if self.flac { codecs.push("flac".to_string()); }
        codecs.push("mp3".to_string());
        codecs.push("mp2".to_string());
        codecs.push("opus".to_string());
        codecs.push("vorbis".to_string());
        codecs.push("alac".to_string());
        codecs.push("pcm_s16le".to_string());
        codecs.push("pcm_s24le".to_string());

        // Deduplicate (dts may appear twice if both dts and dts_hd)
        codecs.sort();
        codecs.dedup();

        codecs
    }

    /// Return the fallback transcoding audio codec.
    ///
    /// When the source audio format is not in the direct-play list, Jellyfin
    /// will transcode. This returns the target codec for that transcode.
    ///
    /// AAC is the universal fallback: hardware-decoded on every device,
    /// good quality at low bitrates, and supported by every HDMI sink.
    pub fn transcode_codec(&self) -> &str {
        "aac"
    }

    /// Detect HDMI audio sink capabilities from ALSA / PipeWire.
    ///
    /// On Raspberry Pi 5 (Debian Bookworm / Trixie), the HDMI audio device
    /// exposes its supported formats via:
    ///   - `/proc/asound/card*/eld*` — EDID-Like Data parsed by ALSA, contains
    ///     the audio SAD (Short Audio Descriptor) blocks from the HDMI sink.
    ///   - `aplay -l` — lists available ALSA playback devices.
    ///
    /// This method parses the ELD data to determine which codecs the connected
    /// HDMI sink (TV, soundbar, AVR) actually supports. Falls back to
    /// `default_safe()` if detection fails.
    pub fn detect_from_system() -> Self {
        info!("Detecting HDMI audio capabilities from system...");

        match Self::parse_alsa_eld() {
            Ok(config) => {
                info!(
                    "HDMI audio detection succeeded: AC3={} EAC3={} DTS={} DTS-HD={} TrueHD={}",
                    config.ac3, config.eac3, config.dts, config.dts_hd, config.truehd
                );
                config
            }
            Err(e) => {
                warn!(
                    "HDMI audio detection failed ({}), falling back to safe defaults (AC3+DTS)",
                    e
                );
                Self::default_safe()
            }
        }
    }

    /// Parse ALSA ELD (EDID-Like Data) files to extract audio capabilities.
    ///
    /// ELD files are at `/proc/asound/card<N>/eld#<M>.<N>` and contain lines like:
    ///   monitor_present     1
    ///   eld_valid           1
    ///   sad0_coding_type    0x01 (PCM)
    ///   sad0_channels       2
    ///   sad1_coding_type    0x02 (AC-3)
    ///   sad1_channels       6
    ///   sad2_coding_type    0x07 (DTS)
    ///   sad2_channels       6
    ///   sad3_coding_type    0x0a (E-AC-3/DD+)
    ///   sad3_channels       8
    ///   sad4_coding_type    0x0c (TrueHD)
    ///   sad4_channels       8
    ///
    /// Coding type values (CEA-861):
    ///   0x01 = LPCM
    ///   0x02 = AC-3
    ///   0x03 = MPEG-1
    ///   0x04 = MP3
    ///   0x05 = MPEG2
    ///   0x06 = AAC-LC
    ///   0x07 = DTS
    ///   0x08 = ATRAC
    ///   0x09 = One Bit Audio (DSD)
    ///   0x0a = Enhanced AC-3 (E-AC-3 / DD+)
    ///   0x0b = DTS-HD
    ///   0x0c = Dolby TrueHD / MLP
    ///   0x0d = DST Audio
    ///   0x0e = WMA Pro
    fn parse_alsa_eld() -> Result<Self, String> {
        // Find all ELD files across all sound cards
        let proc_asound = std::path::Path::new("/proc/asound");
        if !proc_asound.exists() {
            return Err("/proc/asound not found (not Linux or ALSA not loaded)".to_string());
        }

        let mut found_eld = false;
        let mut config = Self {
            ac3: false,
            eac3: false,
            dts: false,
            dts_hd: false,
            truehd: false,
            aac: true,   // always on
            flac: true,   // always on
        };

        // Walk /proc/asound/card*/eld*
        let entries = std::fs::read_dir(proc_asound)
            .map_err(|e| format!("cannot read /proc/asound: {}", e))?;

        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if !name.starts_with("card") {
                continue;
            }

            let card_path = entry.path();
            if let Ok(card_entries) = std::fs::read_dir(&card_path) {
                for card_entry in card_entries.flatten() {
                    let eld_name = card_entry.file_name().to_string_lossy().to_string();
                    if !eld_name.starts_with("eld") {
                        continue;
                    }

                    debug!("Parsing ELD file: {}", card_entry.path().display());

                    if let Ok(contents) = std::fs::read_to_string(card_entry.path()) {
                        // Check that a monitor is actually connected
                        let monitor_present = contents.lines().any(|line| {
                            line.trim().starts_with("monitor_present")
                                && line.contains('1')
                        });
                        let eld_valid = contents.lines().any(|line| {
                            line.trim().starts_with("eld_valid")
                                && line.contains('1')
                        });

                        if !monitor_present || !eld_valid {
                            debug!("ELD {} — no monitor or invalid", eld_name);
                            continue;
                        }

                        found_eld = true;

                        // Parse SAD coding types
                        for line in contents.lines() {
                            let line = line.trim();
                            if !line.contains("coding_type") {
                                continue;
                            }

                            // Extract hex coding type value: "sad0_coding_type 0x02 (AC-3)"
                            let coding_type = Self::extract_coding_type(line);
                            match coding_type {
                                Some(0x02) => {
                                    config.ac3 = true;
                                    debug!("HDMI sink supports AC-3");
                                }
                                Some(0x07) => {
                                    config.dts = true;
                                    debug!("HDMI sink supports DTS");
                                }
                                Some(0x0a) => {
                                    config.eac3 = true;
                                    debug!("HDMI sink supports E-AC-3 (DD+)");
                                }
                                Some(0x0b) => {
                                    config.dts_hd = true;
                                    config.dts = true; // DTS-HD implies DTS core
                                    debug!("HDMI sink supports DTS-HD");
                                }
                                Some(0x0c) => {
                                    config.truehd = true;
                                    config.ac3 = true; // TrueHD implies AC3 core
                                    debug!("HDMI sink supports Dolby TrueHD");
                                }
                                Some(ct) => {
                                    debug!("HDMI sink coding type 0x{:02x} (not a passthrough target)", ct);
                                }
                                None => {}
                            }
                        }
                    }
                }
            }
        }

        if !found_eld {
            return Err("no valid ELD files found (no HDMI monitor connected?)".to_string());
        }

        Ok(config)
    }

    /// Extract the hex coding type value from an ELD line.
    ///
    /// Input:  "sad0_coding_type\t0x02 (AC-3)"
    /// Output: Some(0x02)
    fn extract_coding_type(line: &str) -> Option<u8> {
        // Find "0x" prefix and parse the hex digits after it
        if let Some(hex_pos) = line.find("0x") {
            let hex_str = &line[hex_pos + 2..];
            // Take only hex digits
            let hex_digits: String = hex_str
                .chars()
                .take_while(|c| c.is_ascii_hexdigit())
                .collect();
            if !hex_digits.is_empty() {
                return u8::from_str_radix(&hex_digits, 16).ok();
            }
        }
        None
    }

    /// Return the maximum audio channel count for a given codec.
    ///
    /// Used when building Jellyfin CodecProfile conditions to tell the server
    /// the channel limit for each codec. Exceeding this limit triggers a
    /// server-side downmix transcode.
    pub fn max_channels_for_codec(codec: &str) -> i32 {
        match codec {
            "ac3" => 6,       // 5.1
            "eac3" => 8,      // 7.1 (or 15.1 JOC for Atmos, but 8ch PCM carrier)
            "dts" => 6,       // 5.1
            "truehd" => 8,    // 7.1 (Atmos objects on top)
            "aac" => 8,       // AAC can carry 7.1 but most content is stereo
            "flac" => 8,      // FLAC supports up to 8ch
            "mp3" => 2,       // stereo only
            "opus" => 8,      // Opus supports up to 255ch, but 7.1 is practical
            "vorbis" => 8,    // Vorbis supports up to 255ch
            _ => 2,           // unknown codec — assume stereo
        }
    }

    /// Generate Jellyfin CodecProfile conditions for audio channel limits.
    ///
    /// Returns a list of (codec, max_channels) pairs that should be turned
    /// into CodecProfile entries in device_profile.rs.
    pub fn codec_channel_conditions(&self) -> Vec<(String, i32)> {
        let mut conditions = Vec::new();

        if self.ac3 {
            conditions.push(("ac3".to_string(), Self::max_channels_for_codec("ac3")));
        }
        if self.eac3 {
            conditions.push(("eac3".to_string(), Self::max_channels_for_codec("eac3")));
        }
        if self.dts {
            conditions.push(("dts".to_string(), Self::max_channels_for_codec("dts")));
        }
        if self.truehd {
            conditions.push(("truehd".to_string(), Self::max_channels_for_codec("truehd")));
        }

        conditions
    }
}

impl Default for AudioPassthrough {
    fn default() -> Self {
        Self::default_safe()
    }
}

// =============================================================================
// Display impl for logging / debug output
// =============================================================================

impl std::fmt::Display for AudioPassthrough {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut enabled = Vec::new();
        if self.ac3 { enabled.push("AC3"); }
        if self.eac3 { enabled.push("EAC3"); }
        if self.dts { enabled.push("DTS"); }
        if self.dts_hd { enabled.push("DTS-HD"); }
        if self.truehd { enabled.push("TrueHD"); }
        if self.aac { enabled.push("AAC*"); }
        if self.flac { enabled.push("FLAC*"); }

        if enabled.is_empty() {
            write!(f, "AudioPassthrough(none)")
        } else {
            write!(f, "AudioPassthrough({})", enabled.join(", "))
        }
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_safe_enables_ac3_dts() {
        let config = AudioPassthrough::default_safe();
        assert!(config.ac3);
        assert!(config.dts);
        assert!(!config.eac3);
        assert!(!config.dts_hd);
        assert!(!config.truehd);
        assert!(config.aac);
        assert!(config.flac);
    }

    #[test]
    fn full_enables_everything() {
        let config = AudioPassthrough::full();
        assert!(config.ac3);
        assert!(config.eac3);
        assert!(config.dts);
        assert!(config.dts_hd);
        assert!(config.truehd);
        assert!(config.aac);
        assert!(config.flac);
    }

    #[test]
    fn vlc_args_no_passthrough() {
        let config = AudioPassthrough {
            ac3: false, eac3: false, dts: false,
            dts_hd: false, truehd: false, aac: true, flac: true,
        };
        let args = config.vlc_args();
        // Should have scaletempo but NOT --spdif
        assert!(args.contains(&"--audio-filter".to_string()));
        assert!(args.contains(&"scaletempo".to_string()));
        assert!(!args.contains(&"--spdif".to_string()));
    }

    #[test]
    fn vlc_args_spdif_only() {
        let config = AudioPassthrough::default_safe(); // AC3 + DTS
        let args = config.vlc_args();
        assert!(args.contains(&"--spdif".to_string()));
        // Should NOT force HDMI device (AC3/DTS work over SPDIF)
        assert!(!args.iter().any(|a| a.contains("vc4hdmi")));
    }

    #[test]
    fn vlc_args_hdmi_passthrough() {
        let config = AudioPassthrough::full();
        let args = config.vlc_args();
        assert!(args.contains(&"--spdif".to_string()));
        assert!(args.contains(&"--aout=alsa".to_string()));
        assert!(args.contains(&"--alsa-audio-device=hdmi:CARD=vc4hdmi0".to_string()));
    }

    #[test]
    fn direct_play_codecs_default() {
        let config = AudioPassthrough::default_safe();
        let codecs = config.direct_play_codecs();
        assert!(codecs.contains(&"ac3".to_string()));
        assert!(codecs.contains(&"dts".to_string()));
        assert!(codecs.contains(&"aac".to_string()));
        assert!(codecs.contains(&"flac".to_string()));
        assert!(codecs.contains(&"mp3".to_string()));
        // EAC3 and TrueHD should NOT be listed
        assert!(!codecs.contains(&"eac3".to_string()));
        assert!(!codecs.contains(&"truehd".to_string()));
    }

    #[test]
    fn direct_play_codecs_full() {
        let config = AudioPassthrough::full();
        let codecs = config.direct_play_codecs();
        assert!(codecs.contains(&"ac3".to_string()));
        assert!(codecs.contains(&"eac3".to_string()));
        assert!(codecs.contains(&"dts".to_string()));
        assert!(codecs.contains(&"truehd".to_string()));
        // No duplicates
        let unique: std::collections::HashSet<_> = codecs.iter().collect();
        assert_eq!(codecs.len(), unique.len());
    }

    #[test]
    fn transcode_fallback_is_aac() {
        let config = AudioPassthrough::default_safe();
        assert_eq!(config.transcode_codec(), "aac");
    }

    #[test]
    fn channel_limits() {
        assert_eq!(AudioPassthrough::max_channels_for_codec("ac3"), 6);
        assert_eq!(AudioPassthrough::max_channels_for_codec("eac3"), 8);
        assert_eq!(AudioPassthrough::max_channels_for_codec("dts"), 6);
        assert_eq!(AudioPassthrough::max_channels_for_codec("truehd"), 8);
        assert_eq!(AudioPassthrough::max_channels_for_codec("mp3"), 2);
        assert_eq!(AudioPassthrough::max_channels_for_codec("unknown"), 2);
    }

    #[test]
    fn codec_channel_conditions_match_enabled() {
        let config = AudioPassthrough::default_safe();
        let conditions = config.codec_channel_conditions();
        // AC3 and DTS should be present
        assert!(conditions.iter().any(|(c, _)| c == "ac3"));
        assert!(conditions.iter().any(|(c, _)| c == "dts"));
        // EAC3 and TrueHD should NOT be present
        assert!(!conditions.iter().any(|(c, _)| c == "eac3"));
        assert!(!conditions.iter().any(|(c, _)| c == "truehd"));
    }

    #[test]
    fn extract_coding_type_hex() {
        assert_eq!(AudioPassthrough::extract_coding_type("sad0_coding_type\t0x02 (AC-3)"), Some(0x02));
        assert_eq!(AudioPassthrough::extract_coding_type("sad3_coding_type\t0x0a (E-AC-3/DD+)"), Some(0x0a));
        assert_eq!(AudioPassthrough::extract_coding_type("sad4_coding_type\t0x0c (TrueHD)"), Some(0x0c));
        assert_eq!(AudioPassthrough::extract_coding_type("no hex here"), None);
    }

    #[test]
    fn display_impl() {
        let config = AudioPassthrough::default_safe();
        let s = format!("{}", config);
        assert!(s.contains("AC3"));
        assert!(s.contains("DTS"));
        assert!(!s.contains("TrueHD"));
    }

    #[test]
    fn detect_from_system_falls_back_gracefully() {
        // On macOS or any system without /proc/asound, this should fall back
        // to default_safe() without panicking.
        let config = AudioPassthrough::detect_from_system();
        // Should at minimum have AC3 + DTS (from fallback)
        assert!(config.ac3);
        assert!(config.dts);
    }
}
